const SEARCH_POST_REQUEST = "SEARCH_POST_REQUEST";
const SEARCH_POST_SUCCESS = "SEARCH_POST_SUCCESS";
const SEARCH_POST_FAULIER = "SEARCH_POST_FAULIER";

export { SEARCH_POST_REQUEST, SEARCH_POST_SUCCESS, SEARCH_POST_FAULIER };
