const LOGIN_GET_REQUEST = "LOGIN_POST_REQUEST";
const LOGIN_GET_SUCCESSS = "LOGIN_POST_SUCCESS";
const LOGIN_GET_FAUILUIER = "LOGIN_POST_FAUILUIER";

const POSTS_POST_REQUEST = "POSTS_POST_REQUEST";
const POSTS_POST_SUCCESS = "POSTS_POST_SUCCESS";
const POSTS_POST_FAILURE = "POSTS_POST_FAILURE";

const POSTS_GET_REQUEST = "POSTS_GET_REQUEST";
const POSTS_GET_SUCCESS = "POSTS_GET_SUCCESS";
const POSTS_GET_FAILURE = "POSTS_GET_FAILURE";

const POSTS_LIKES_REQUEST = "POSTS_LIKES_REQUEST";
const POSTS_LIKES_SUCCESS = "POSTS_LIKES_SUCCESS";
const POSTS_LIKES_FAILURE = "POSTS_LIKES_FAILURE";

export {
  LOGIN_GET_REQUEST,
  LOGIN_GET_SUCCESSS,
  LOGIN_GET_FAUILUIER,
  POSTS_POST_REQUEST,
  POSTS_POST_SUCCESS,
  POSTS_POST_FAILURE,
  POSTS_GET_REQUEST,
  POSTS_GET_SUCCESS,
  POSTS_GET_FAILURE,
  POSTS_LIKES_REQUEST,
  POSTS_LIKES_SUCCESS,
  POSTS_LIKES_FAILURE,
};
