const LOGIN_POST_REQUEST = "LOGIN_POST_REQUEST";
const LOGIN_POST_SUCCESSS = "LOGIN_POST_SUCCESS";
const LOGIN_POST_FAUILUIER = "LOGIN_POST_FAUILUIER";
const COUNTRY_POST_REQUEST = "COUNTRY_POST_REQUEST";
const COUNTRY_POST_SUCCESSS = "COUNTRY_POST_SUCCESSS";
const COUNTRY_POST_FAUILUIER = "COUNTRY_POST_FAUILUIER";
const CITY_POST_REQUEST = "CITY_POST_REQUEST";
const CITY_POST_SUCCESSS = "CITY_POST_SUCCESSS";
const CITY_POST_FAUILUIER = "CITY_POST_FAUILUIER";
const CITY_GET_REQUEST = "CITY_GET_REQUEST";
const CITY_GET_SUCCESSS = "CITY_GET_SUCCESSS";
const CITY_GET_FAUILUIER = "CITY_GET_FAUILUIER";
const COUNTRY_GET_REQUEST = "COUNTRY_GET_REQUEST";
const COUNTRY_GET_SUCCESSS = "COUNTRY_GET_SUCCESSS";
const COUNTRY_GET_FAUILUIER = "COUNTRY_GET_FAUILUIER";
const DELETE_CITY_REQUEST = "DELETE_CITY_REQUEST";
const DELETE_CITY_SUCCESS = "DELETE_CITY_SUCCESS";
const DELETE_CITY_FAUILUIER = "DELETE_CITY_FAUILUIER";
const UPDATE_REQUEST = "UPDATE_REQUEST";
const UPDATE_SUCCESS = "UPDATE_SUCCESS";
const UPDATE_FAUILUIER = "UPDATE_FAUILUIER";

export {
  LOGIN_POST_REQUEST,
  LOGIN_POST_SUCCESSS,
  LOGIN_POST_FAUILUIER,
  COUNTRY_POST_REQUEST,
  COUNTRY_POST_SUCCESSS,
  COUNTRY_POST_FAUILUIER,
  COUNTRY_GET_REQUEST,
  COUNTRY_GET_SUCCESSS,
  COUNTRY_GET_FAUILUIER,
  CITY_POST_REQUEST,
  CITY_POST_SUCCESSS,
  CITY_POST_FAUILUIER,
  CITY_GET_REQUEST,
  CITY_GET_SUCCESSS,
  CITY_GET_FAUILUIER,
  DELETE_CITY_REQUEST,
  DELETE_CITY_SUCCESS,
  DELETE_CITY_FAUILUIER,
  UPDATE_REQUEST,
  UPDATE_SUCCESS,
  UPDATE_FAUILUIER,
};
