const LOGIN_GET_REQUEST = "LOGIN_POST_REQUEST";
const LOGIN_GET_SUCCESSS = "LOGIN_POST_SUCCESS";
const LOGIN_GET_FAUILUIER = "LOGIN_POST_FAUILUIER";
export { LOGIN_GET_REQUEST, LOGIN_GET_SUCCESSS, LOGIN_GET_FAUILUIER };
