const COUNTRY_GET_REQUEST = "COUNTRY_GET_REQUEST";
const COUNTRY_GET_SUCCESSS = "COUNTRY_GET_SUCCESSS";
const COUNTRY_GET_FAUILUIER = "COUNTRY_GET_FAUILUIER";

export { COUNTRY_GET_REQUEST, COUNTRY_GET_SUCCESSS, COUNTRY_GET_FAUILUIER };
