const LOGIN_POST_REQUEST = "LOGIN_POST_REQUEST";
const LOGIN_POST_SUCCESS = "LOGIN_POST_SUCCESS";
const LOGIN_POST_FAULIER = "LOGIN_POST_FAULIER";

export { LOGIN_POST_REQUEST, LOGIN_POST_SUCCESS, LOGIN_POST_FAULIER };
